# Generated by Django 5.0.3 on 2024-04-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/villa_images/')),
                ('area', models.PositiveSmallIntegerField(help_text='Метр в квадрате')),
                ('security', models.PositiveSmallIntegerField(choices=[(1, 'Охраняемая территория'), (2, 'Не охраняемая территория')])),
                ('description', models.TextField()),
                ('floor_number', models.PositiveSmallIntegerField()),
                ('bedroom', models.PositiveSmallIntegerField()),
                ('bathroom', models.PositiveSmallIntegerField()),
                ('parking_space_capacity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('address', models.CharField(max_length=225)),
                ('zip_code', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paymentmethod')),
            ],
        ),
    ]
