# Generated by Django 5.0.3 on 2024-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
