# Generated by Django 5.0.3 on 2024-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Обычный пользователь'), (2, 'Менеджер')], default=1),
        ),
    ]
